services:
  app:
    build: .
    container_name: task-management-system-task
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/task-management-system-task-db
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: task-management-system-task-db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
